### PR TITLE
Update dockerfile 

### PR DESCRIPTION
**Pull request by NDelventhal**
Added Python packages

### CODE REVIEW

**Comment by joachim-gassen** [comment]
Thanks! Merged

**Comment by mpff** [comment]
Anybody else getting an error when building their docker environment? Mine throws an error when trying to install the `math` package.

```
Step 14/23 : RUN pip3 install seaborn math
 ---> Running in c441424ab5f8
Requirement already satisfied: seaborn in /usr/local/lib/python3.5/dist-packages
Collecting math
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/math/
The command '/bin/sh -c pip3 install seaborn math' returned a non-zero code: 2
```

**Comment by joachim-gassen** [comment]
I am not a Python guru but this looks like a typo to me. Could it be that Niall meant to include the package `maths`? Could you please check and issue a PR if it works?

**Comment by mpff** [comment]
As `maths` did not work, I am thinking that Niall indeed wanted to include the `math` package. However, `math` is a Python built-in, so it comes with the base python installation and doesn't need to/can't be installed via pip.

I'll remove it and try building the environment and running `make all`. If everything passes I'll issue a PR.

**Comment by NDelventhal** [comment]
Yes, I can confirm my intention was to install the `math` package and missed out on considering, if it comes along with Python’s standard library.  I apologise for any inconvience this has caused.

**Pull request merged**
